[project]
name = "push-to-talk"
version = "0.1.0"
description = "Push to talk example"
requires-python = ">=3.10"
dependencies = [
    "pipecat-ai[daily,deepgram,openai,silero,cartesia,runner]>=0.0.82",
    "pipecatcloud>=0.2.4"
]

[dependency-groups]
dev = [
    "ruff~=0.12.1",
]

[tool.ruff]
line-length = 100
[tool.ruff.lint]
select = ["I"]