agent_name = "word-wrangler-twilio"
image = "your_username/word-wrangler-twilio:0.1"
image_credentials = "your_dockerhub_pull_secret"
secret_set = "word-wrangler-twilio-secrets"
enable_krisp = true
agent_profile = "agent-1x"

[scaling]
	min_agents = 1
