agent_name = "smallwebrtc-poc"
image = "your_username/pipecat-smallwebrtc:latest"
image_credentials = "smallwebrtc-pull-secret"
secret_set = "smallwebrtc-secrets"
enable_krisp = true

[scaling]
	min_agents = 1
