[project]
name = "word-wrangler"
version = "0.1.0"
description = "Word Wrangler guessing game powered by Gemini"
requires-python = ">=3.10"
dependencies = [
    "pipecat-ai[daily,silero,google,local-smart-turn-v3,runner]>=0.0.90",
    "pipecatcloud>=0.2.6"
]

[dependency-groups]
dev = [
    "ruff~=0.12.1",
]

[tool.ruff]
line-length = 100
[tool.ruff.lint]
select = ["I"]